# Generated by Django 4.2.8 on 2023-12-31 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hremployeemore_remove_employeemore_departmentmanager_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('objectPerspective', models.CharField(choices=[('Financial', 'Financial'), ('Customer', 'Customer'), ('Process Improvement', 'Process Improvement'), ('People', 'People')], max_length=255)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupObjectInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualDate', models.DateField()),
                ('objectDescription', models.TextField()),
                ('kpiMeasure', models.TextField()),
                ('weight', models.FloatField()),
                ('directHeadReview', models.BooleanField(default=False)),
                ('departmentManagerReview', models.BooleanField(default=False)),
                ('hrReview', models.BooleanField(default=False)),
                ('directHeadNote', models.TextField()),
                ('departmentManagerNote', models.TextField()),
                ('hrNote', models.TextField()),
                ('creationDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPerspectiveBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectPerspective', models.CharField(choices=[('Financial', 'Financial'), ('Customer', 'Customer'), ('Process Improvement', 'Process Improvement'), ('People', 'People')], max_length=255)),
                ('target', models.IntegerField()),
                ('targetDate', models.DateField()),
                ('monitoringFrequency', models.CharField(choices=[('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly')], max_length=255)),
                ('instanceCount', models.IntegerField()),
                ('totalInstances', models.IntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('groupObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupobject')),
                ('groupObjectInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupobjectinstance')),
            ],
        ),
        migrations.DeleteModel(
            name='Appraisal',
        ),
        migrations.DeleteModel(
            name='Objectives',
        ),
    ]
