# Generated by Django 4.2.8 on 2023-12-31 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groupobject_groupobjectinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='groupObjectInstance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.groupobjectinstance'),
        ),
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='instanceCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='targetDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='totalInstances',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
