# Generated by Django 4.2.8 on 2023-12-31 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hremployeemore_remove_employeemore_departmentmanager_and_more'),
        ('core', '0005_alter_objectperspectiveblueprint_groupobjectinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectperspectiveblueprint',
            name='groupObjectInstance',
        ),
        migrations.AddField(
            model_name='groupobjectinstance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='groupobjectinstance',
            name='groubObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.groupobject'),
        ),
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='groupObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.groupobject'),
        ),
        migrations.CreateModel(
            name='BlueprintObjectInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.objectperspectiveblueprint')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('objectInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.groupobjectinstance')),
            ],
        ),
    ]
