# Generated by Django 4.2.8 on 2023-12-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hremployeemore_remove_employeemore_departmentmanager_and_more'),
        ('core', '0006_remove_objectperspectiveblueprint_groupobjectinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintObjectInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='groupobjectinstance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groubObjectInstance', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='groupobjectinstance',
            name='groubObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groubObjectInstance', to='core.groupobject'),
        ),
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Blueprint', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='groupObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprint', to='core.groupobject'),
        ),
        migrations.DeleteModel(
            name='BlueprintObjectInstances',
        ),
        migrations.AddField(
            model_name='blueprintobjectinstance',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlueprintObjectInstance', to='core.objectperspectiveblueprint'),
        ),
        migrations.AddField(
            model_name='blueprintobjectinstance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BlueprintObjectInstance', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='blueprintobjectinstance',
            name='objectInstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlueprintObjectInstance', to='core.groupobjectinstance'),
        ),
    ]
