# Generated by Django 4.2.8 on 2023-12-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blueprintobjectinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='monitoringFrequency',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly')], max_length=255),
        ),
    ]
