# Generated by Django 4.2.8 on 2023-12-31 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_objectperspectiveblueprint_monitoringfrequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupobjectinstance',
            name='departmentManagerNote',
        ),
        migrations.RemoveField(
            model_name='groupobjectinstance',
            name='directHeadNote',
        ),
        migrations.RemoveField(
            model_name='groupobjectinstance',
            name='groubObject',
        ),
        migrations.RemoveField(
            model_name='groupobjectinstance',
            name='hrNote',
        ),
        migrations.CreateModel(
            name='InstanceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('groubObjectInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='core.groupobjectinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instanceNote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
