# Generated by Django 4.2.8 on 2024-01-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_groupobjectinstance_departmentmanagernote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancenotes',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
