# Generated by Django 4.2.8 on 2024-01-01 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_instancenotes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectperspectiveblueprint',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupobjectinstance',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
