# Generated by Django 4.2.8 on 2024-01-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_objectperspectiveblueprint_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectperspectiveblueprint',
            name='totalInstances',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
