# Generated by Django 4.2.8 on 2024-01-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_departmentmanagermore_manageddepartment'),
        ('core', '0012_alter_objectperspectiveblueprint_totalinstances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintobjectinstance',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlueprintInstance', to='core.objectperspectiveblueprint'),
        ),
        migrations.AlterField(
            model_name='blueprintobjectinstance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BlueprintInstance', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='blueprintobjectinstance',
            name='objectInstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlueprintInstance', to='core.groupobjectinstance'),
        ),
    ]
