# Generated by Django 4.2.8 on 2024-01-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department_departmentmanagermore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmanagermore',
            name='managedDepartment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='accounts.department'),
        ),
    ]
