# Generated by Django 4.2.8 on 2023-12-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employeemore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemore',
            name='user',
        ),
        migrations.AlterField(
            model_name='employeemore',
            name='empSupervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='accounts.supervisor'),
        ),
    ]
