# Generated by Django 4.2.8 on 2023-12-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employeemore_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemore',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
