# Generated by Django 4.2.8 on 2023-12-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employeemore_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisorDepartmentManager', to='accounts.departmentmanager')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
