# Generated by Django 4.2.8 on 2023-12-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supervisormore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectHeadMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directHeadDepartmentManager', to='accounts.departmentmanager')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisormore',
            name='departmentManager',
        ),
        migrations.RemoveField(
            model_name='supervisormore',
            name='user',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.CreateModel(
            name='DirectHead',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.RemoveField(
            model_name='employeemore',
            name='empSupervisor',
        ),
        migrations.DeleteModel(
            name='SupervisorMore',
        ),
        migrations.AddField(
            model_name='employeemore',
            name='empDirectHead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directHead', to='accounts.directhead'),
        ),
    ]
